### ISSUE TITLE
導入選課資料功能

### ISSUE THREAD

**Issue by taifu9920** [JiaxuanTW/NUK-Course-Selection-Tool#26]
建議這功能可以新增上去
方便在每次選課過程有變動的話
可以直接導入先前下載的選課內容來修改
這邊有我草草的程式碼
直接加入static/js/table.js最底下就可以用了
注意這程式碼只考慮方便每次更新移植
所以沒顧慮效能或美觀甚至註解(偷懶的部分xD)

	//Extra Added by Driftie
	let dropbox;

	dropbox = document.getElementsByClassName("row h-100")[0];
	dropbox.addEventListener("dragenter", dragenter, false);
	dropbox.addEventListener("dragover", dragover, false);
	dropbox.addEventListener("drop", drop, false);

	function dragenter(e) {
	  e.stopPropagation();
	  e.preventDefault();
	};

	function dragover(e) {
	  e.stopPropagation();
	  e.preventDefault();
	};
	var contents;
	const reader = new FileReader();
	function drop(e) {
	  e.stopPropagation();
	  e.preventDefault();

	  const dt = e.dataTransfer;
	  const files = dt.files;
	  
	  reader.onload = process
	  
	  reader.readAsText(files[0]);
	};

	function process(event){
		contents = event.target.result.trim().split("\r\n").slice(1);
		target = []
		for (i = 1; i < 5; i++){
			for (var o of contents){
				if (document.getElementById(o.split(", ")[1] + i.toString()) != null){
					target.push(document.getElementById(o.split(", ")[1] + i.toString()))
				}
			}
		}
		for (var i of target){
			i.click()
		}
	}

添加後啟動，只要將下載的csv檔案拖拉進去網頁就能載入了

**Comment by JiaxuanTW** [comment]
今天才看到這個 Issue，選課時間都過得差不多了哈哈
謝謝你提出這個新功能想法，還附上了程式碼！
大致上沒問題，我沒有改動太多
但我也發現若在已有選擇課程的情況下拖曳進來會導致顯示錯誤
我加上`deleteAll()`（清除已選課程）先在前執行，以防錯誤

**Comment by JiaxuanTW** [comment]
話說你也很不簡單欸，還來看這些程式碼
我們當初 Javascript、Flask 學不深都寫得亂亂的
好快一學年就過了~

**Comment by taifu9920** [comment]
> 話說你也很不簡單欸，還來看這些程式碼
> 我們當初 Javascript、Flask 學不深都寫得亂亂的
> 好快一學年就過了~

xD也沒看多少程式碼
翻網頁標籤的名稱來寫的
因為有時候選不到課還要塞其他課程
沒這功能要點好久來重新規劃

至於JavaScript、Flask高中我就開始用了
寫到現在的經驗應該不至於太糟糕吧xD
